#!/bin/bash
rake db:drop
rails destroy model Program
rails destroy model Task
rails destroy model ProgramItem
rails db:create

rails g model Program title description:text
rails g model Task title description:text 
rails g model ProgramItem program_id:integer task_id:integer position:integer program:references task:references
rails g model Enrollment state:integer program:references task:references user:references

# echo "on the following migration
# read -n1 -r -p "Do the above line, and Press space to continue..." key

echo "class Program < ApplicationRecord\n  has_many :program_items, dependent: :destroy"
echo "has_many :tasks, through: :program_items\nend"

echo "class ProgramItem < ApplicationRecord\n  belongs_to :program\n  belong_to :task\n"
echo "  validates :task_id, :presence => true\n  validates :position, uniqueness: true\nend"

echo "class Task < ApplicationRecord\n  has_many :program_items\nend"

rails db:migrate
